import type { Metadata } from "next";
import "./globals.css";
import NavBar from "../../components/NavBar";
import styles from "./layout.module.css"


export const metadata: Metadata = {
  title: "Santa-Kaya Grow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={styles.bodypage}>
        
          <NavBar/>
        {children}
        </body>
    </html>
  );
}
